# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard Kotze - Software Engineer
description: > # this means to ignore newlines until "baseurl:"
  Opinions about software engineering and sharing knowledge about technologies I learn
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.richardkotze.com" # the base hostname & protocol for your site
tobe_url: "https://www.richardkotze.com"
old_url: "http://www.richardkotze.com"
twitter_username: richardkotze
github_username:  rkotze
google_username:  109155264212733458222?rel=author
facebook_username:  webdesign.develop

paginate: 12
permalink: "/:categories/:title"

# Build settings
markdown: kramdown

exclude: ["readme.md"]

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from